### ISSUE TITLE
Is there Yii2 Extension for this!!!

### ISSUE THREAD

**Issue by aidonsnous** [BeingTomGreen/IP-User-Location#2]
Hello!!!
I tried to get to use danio extension(Yii2) forked form this project but got a problem of accessing the response information. Here is where I tried to describe the problem: [http://www.yiiframework.com/forum/index.php/topic/70605-danio1024ip-user-location/page__gopid__299274#entry299274](Yii extension forum).

So I would like to know if there is a possibility of using your extension. Thanks

**Comment by BeingTomGreen** [comment]
I'm afraid I'm not super familiar with Yii2, or the the forks of this project. That said having looked at the docs believe the error you're seeing is related to the way you're manipulating sessions in Yii2.

According to the docs to access session data you'd need to do one of the following:

```php
$language = $session->get('language');
$language = $session['language'];
$language = isset($_SESSION['language']) ? $_SESSION['language'] : null;
```

And to set them:

```php
$session->set('language', 'en-US');
$session['language'] = 'en-US';
$_SESSION['language'] = 'en-US';
```

Putting this together, why not try:

```php
$ipInfo = new ipInfo('Mykey', 'json');

try {
    Yii::$app->session->set('Countryinfo', json_decode($ipInfo->getCountry('154.70.157.3'));
}
catch(Exception $e)
{
    Yii::$app->session->set('Countryinfo', null);
}

if($session->has('Countryinfo')){
    echo 'ok';
}
```

**Comment by BeingTomGreen** [comment]
@MagSag this isn't a package for any particular framework, it's a (very, very) basic class to expose the functionality offered by IPInfoDB.

As far as I can tell @danio1024's fork doesn't really do anything differently.
